baseURL: https://www.sxrup.xyz/
title: Syrup's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Syrup's Blog
  description: "| 💻 Programmer | 👾 Backend Dev | 😻 Cat Lovers |"
  keywords: [Blog, Portfolio]
  author: Syrup
  # author: ["Me", "You"] # multiple authors
  images: ["img/profile.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "img/profile.png"
    favicon16x16: "img/profile.png"
    favicon32x32: "img/profile.png"
    apple_touch_icon: "img/profile.png"
    safari_pinned_tab: "img/profile.png"

  label:
    text: "Home"
    icon: /img/profile.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Syrup
    # subtitle: "Hello, I go by Syrup on the internet. I'm a backend developer and I'm still in the high school. I love to write about programming, tech, and sometimes about my life. I'm also a fan of open-source software and I'm always looking for ways to contribute to the community. I hope you enjoy reading my blog posts and find them helpful. If you have any questions or want to contact me, feel free to reach out to me on social media or via email. It's below here ⬇"
    subtitle: "| 💻 Programmer | 👾 Backend Dev | 😻 Cat Lovers |"
    imageUrl: "img/profile.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Kyawoo"
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons:
    - name: discord
      url: "https://discord.com/users/681843628317868049"
    - name: github
      url: "https://github.com/Syrup"
    - name: email
      url: "mailto:goodgamersz665@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Syrup/site/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: "🔍 Search"
      url: /search/
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: true
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
  goldmark:
    renderer:
      unsafe: true
